sestions: 
  - session_type: vacancy
    input_data: |
      [{'Quarter': 'Q2 2022', 'Overall': 18.01, 'Class A': 21.1, 'Class B': 17.0},
      {'Quarter': 'Q3 2022', 'Overall': 17.7, 'Class A': 20.8, 'Class B': 16.6},
      {'Quarter': 'Q4 2022', 'Overall': 17.49, 'Class A': 19.7, 'Class B': 17.2},
      {'Quarter': 'Q1 2023', 'Overall': 17.6, 'Class A': 20.4, 'Class B': 16.8},
      {'Quarter': 'Q2 2023', 'Overall': 17.72, 'Class A': 20.4, 'Class B': 17.1},
      {'Quarter': 'Q3 2023', 'Overall': 17.99, 'Class A': 21.1, 'Class B': 17.1},
      {'Quarter': 'Q4 2023', 'Overall': 17.95, 'Class A': 21.0, 'Class B': 17.2},
      {'Quarter': 'Q1 2024', 'Overall': 18.36, 'Class A': 20.9, 'Class B': 18.1},
      {'Quarter': 'Q2 2024', 'Overall': 18.96, 'Class A': 22.3, 'Class B': 17.9},
      {'Quarter': 'Q3 2024', 'Overall': 19.19, 'Class A': 22.0, 'Class B': 18.7},
      {'Quarter': 'Q4 2024', 'Overall': 19.13, 'Class A': 21.8, 'Class B': 18.8},
      {'Quarter': 'Q1 2025', 'Overall': 18.65, 'Class A': 21.0, 'Class B': 18.5},
      {'Quarter': 'Q2 2025', 'Overall': 18.29, 'Class A': 20.4, 'Class B': 18.4}]
  - session_type: availability_rate
    input_data: |
      [{'Quarter': 'Q2 2022', 'Overall': 4.0, 'Direct': 3.7, 'Sublease': 0.3},
      {'Quarter': 'Q3 2022', 'Overall': 3.8, 'Direct': 3.4, 'Sublease': 0.4},
      {'Quarter': 'Q4 2022', 'Overall': 4.0, 'Direct': 3.7, 'Sublease': 0.3},
      {'Quarter': 'Q1 2023', 'Overall': 4.2, 'Direct': 3.8, 'Sublease': 0.3},
      {'Quarter': 'Q2 2023', 'Overall': 4.3, 'Direct': 3.9, 'Sublease': 0.4},
      {'Quarter': 'Q3 2023', 'Overall': 5.0, 'Direct': 4.6, 'Sublease': 0.4},
      {'Quarter': 'Q4 2023', 'Overall': 5.1, 'Direct': 4.7, 'Sublease': 0.4},
      {'Quarter': 'Q1 2024', 'Overall': 5.6, 'Direct': 5.0, 'Sublease': 0.6},
      {'Quarter': 'Q2 2024', 'Overall': 5.6, 'Direct': 5.1, 'Sublease': 0.5},
      {'Quarter': 'Q3 2024', 'Overall': 5.7, 'Direct': 5.0, 'Sublease': 0.7},
      {'Quarter': 'Q4 2024', 'Overall': 5.4, 'Direct': 4.7, 'Sublease': 0.7},
      {'Quarter': 'Q1 2025', 'Overall': 5.7, 'Direct': 5.0, 'Sublease': 0.7},
      {'Quarter': 'Q2 2025', 'Overall': 6.2, 'Direct': 5.4, 'Sublease': 0.8}]
  - session_type: construction_activity
    input_data: |
      [{'Quarter': 'Q2 2022', 'Under Construction': 5938452, 'Deliveries': 560624},
      {'Quarter': 'Q3 2022', 'Under Construction': 9079552, 'Deliveries': 1927955},
      {'Quarter': 'Q4 2022', 'Under Construction': 7698808, 'Deliveries': 3412618},
      {'Quarter': 'Q1 2023', 'Under Construction': 7926913, 'Deliveries': 148999},
      {'Quarter': 'Q2 2023', 'Under Construction': 9066970, 'Deliveries': 1478873},
      {'Quarter': 'Q3 2023', 'Under Construction': 5158914, 'Deliveries': 4701856},
      {'Quarter': 'Q4 2023', 'Under Construction': 3713541, 'Deliveries': 2162793},
      {'Quarter': 'Q1 2024', 'Under Construction': 2364975, 'Deliveries': 1630980},
      {'Quarter': 'Q2 2024', 'Under Construction': 3257068, 'Deliveries': 408617},
      {'Quarter': 'Q3 2024', 'Under Construction': 2745432, 'Deliveries': 1036960},
      {'Quarter': 'Q4 2024', 'Under Construction': 3082393, 'Deliveries': 89039},
      {'Quarter': 'Q1 2025', 'Under Construction': 3148889, 'Deliveries': 947692},
      {'Quarter': 'Q2 2025', 'Under Construction': 3517819, 'Deliveries': 1118560}]
  - session_type: market_overview
    input_data: |
      [{'Quarter': 'Q2 2022',
        'Net Absorption': 2345448,
        'Deliveries': 560624,
        'Vacancy Rate': 3.1},
      {'Quarter': 'Q3 2022',
        'Net Absorption': 2503359,
        'Deliveries': 1927955,
        'Vacancy Rate': 2.8},
      {'Quarter': 'Q4 2022',
        'Net Absorption': 1736749,
        'Deliveries': 3412618,
        'Vacancy Rate': 3.4},
      {'Quarter': 'Q1 2023',
        'Net Absorption': 1068724,
        'Deliveries': 148999,
        'Vacancy Rate': 3.2},
      {'Quarter': 'Q2 2023',
        'Net Absorption': 373975,
        'Deliveries': 1478873,
        'Vacancy Rate': 3.5},
      {'Quarter': 'Q3 2023',
        'Net Absorption': 1790289,
        'Deliveries': 4701856,
        'Vacancy Rate': 4.3},
      {'Quarter': 'Q4 2023',
        'Net Absorption': 1740135,
        'Deliveries': 2162793,
        'Vacancy Rate': 4.4},
      {'Quarter': 'Q1 2024',
        'Net Absorption': 1428393,
        'Deliveries': 1630980,
        'Vacancy Rate': 4.5},
      {'Quarter': 'Q2 2024',
        'Net Absorption': 722289,
        'Deliveries': 408617,
        'Vacancy Rate': 4.4},
      {'Quarter': 'Q3 2024',
        'Net Absorption': 1007113,
        'Deliveries': 1036960,
        'Vacancy Rate': 4.4},
      {'Quarter': 'Q4 2024',
        'Net Absorption': 1269837,
        'Deliveries': 89039,
        'Vacancy Rate': 4.0},
      {'Quarter': 'Q1 2025',
        'Net Absorption': 1495710,
        'Deliveries': 947692,
        'Vacancy Rate': 3.9},
      {'Quarter': 'Q2 2025',
        'Net Absorption': 528351,
        'Deliveries': 1118560,
        'Vacancy Rate': 4.0}]
  - session_type: asking_rent
    input_data: |
      [{'Quarter': 'Q2 2022', 'Series 1': 6.43},
      {'Quarter': 'Q3 2022', 'Series 1': 7.15},
      {'Quarter': 'Q4 2022', 'Series 1': 7.7},
      {'Quarter': 'Q1 2023', 'Series 1': 8.3},
      {'Quarter': 'Q2 2023', 'Series 1': 8.83},
      {'Quarter': 'Q3 2023', 'Series 1': 9.01},
      {'Quarter': 'Q4 2023', 'Series 1': 9.2},
      {'Quarter': 'Q1 2024', 'Series 1': 9.23},
      {'Quarter': 'Q2 2024', 'Series 1': 9.33},
      {'Quarter': 'Q3 2024', 'Series 1': 9.11},
      {'Quarter': 'Q4 2024', 'Series 1': 9.19},
      {'Quarter': 'Q1 2025', 'Series 1': 9.5},
      {'Quarter': 'Q2 2025', 'Series 1': 9.87}]
  - session_type: net_absorption
    input_data: |
      [{'Quarter': 'Q2 2022',
        'Net Absorption': 2345448,
        'Rolling 4Q Avg.': 2345448.0},
      {'Quarter': 'Q3 2022',
        'Net Absorption': 2503359,
        'Rolling 4Q Avg.': 2424403.5},
      {'Quarter': 'Q4 2022',
        'Net Absorption': 1736749,
        'Rolling 4Q Avg.': 2195185.333},
      {'Quarter': 'Q1 2023',
        'Net Absorption': 1068724,
        'Rolling 4Q Avg.': 1913570.0},
      {'Quarter': 'Q2 2023',
        'Net Absorption': 373975,
        'Rolling 4Q Avg.': 1420701.75},
      {'Quarter': 'Q3 2023',
        'Net Absorption': 1790289,
        'Rolling 4Q Avg.': 1242434.25},
      {'Quarter': 'Q4 2023',
        'Net Absorption': 1740135,
        'Rolling 4Q Avg.': 1243280.75},
      {'Quarter': 'Q1 2024',
        'Net Absorption': 1428393,
        'Rolling 4Q Avg.': 1333198.0},
      {'Quarter': 'Q2 2024',
        'Net Absorption': 722289,
        'Rolling 4Q Avg.': 1420276.5},
      {'Quarter': 'Q3 2024',
        'Net Absorption': 1007113,
        'Rolling 4Q Avg.': 1224482.5},
      {'Quarter': 'Q4 2024',
        'Net Absorption': 1269837,
        'Rolling 4Q Avg.': 1106908.0},
      {'Quarter': 'Q1 2025',
        'Net Absorption': 1495710,
        'Rolling 4Q Avg.': 1123737.25},
      {'Quarter': 'Q2 2025',
        'Net Absorption': 528351,
        'Rolling 4Q Avg.': 1075252.75}]
  - session_type: leasing_activity
    input_data: |
      [{'Quarter': 'Q2 2022', 'Overall': 2452750},
      {'Quarter': 'Q3 2022', 'Overall': 3401952},
      {'Quarter': 'Q4 2022', 'Overall': 1588869},
      {'Quarter': 'Q1 2023', 'Overall': 2931792},
      {'Quarter': 'Q2 2023', 'Overall': 3051629},
      {'Quarter': 'Q3 2023', 'Overall': 2773167},
      {'Quarter': 'Q4 2023', 'Overall': 2147389},
      {'Quarter': 'Q1 2024', 'Overall': 1708461},
      {'Quarter': 'Q2 2024', 'Overall': 1176800},
      {'Quarter': 'Q3 2024', 'Overall': 2488797},
      {'Quarter': 'Q4 2024', 'Overall': 2933662},
      {'Quarter': 'Q1 2025', 'Overall': 1742074},
      {'Quarter': 'Q2 2025', 'Overall': 1525517}]